"""pictures column

Revision ID: 1bc8e5bdba0a
Revises: f946a4dcade3
Create Date: 2024-02-12 12:07:45.726006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc8e5bdba0a'
down_revision = 'f946a4dcade3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventors', schema=None) as batch_op:
        batch_op.drop_column('group_image')

    # ### end Alembic commands ###
