"""models and tables

Revision ID: 6cb23fb57bae
Revises: 
Create Date: 2024-02-06 12:30:32.246671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb23fb57bae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('patent_status', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventors_patent',
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('inventors_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventors_id'], ['inventors.id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.PrimaryKeyConstraint('patent_id', 'inventors_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventors_patent')
    op.drop_table('patents')
    op.drop_table('users')
    op.drop_table('inventors')
    op.drop_table('classifications')
    # ### end Alembic commands ###
